services:
  - type: web
    name: interestingtechforvi
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5000
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    rootDir: .
    disk:
      name: data
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1

